# This file defines the SA and its associated roles that is needed by the Workflows EventListener
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-workflows-el-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-workflows-el-binding
subjects:
  - kind: ServiceAccount
    name: tekton-workflows-el-sa
    namespace: tekton-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-example-eventlistener-clusterbinding
subjects:
  - kind: ServiceAccount
    name: tekton-workflows-el-sa
    namespace: tekton-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---

