apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: workflows-listener
  namespace: tekton-workflows
spec:
  serviceAccountName: tekton-workflows-el-sa
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
  labelSelector:
    matchLabels:
      managed-by: tekton-workflows
